### ISSUE TITLE
GMCP support

### ISSUE THREAD

**Issue by Brenex** [demonnic/YATCO#8]
I have come across two scripts that help add support for GMCP in to YATCO. The first work's out of the box, is more simple, and respects YATCO's settings for gag and timestamp:

https://www.dropbox.com/s/31qbex4f9eyg0aj/GMCPChat.trigger.xml?dl=0

The second has nameDB support (which works) but does not respect YATCO options for gag even if gag is set to true in both YATCO and the script itself. It also does not appear with timestamps: 

https://www.dropbox.com/s/76lkj7kvj6b6s29/GMCPChat.xml?dl=0

Any thoughts towards including GMCP support in YATCO natively?

**Comment by demonnic** [comment]
I'm for it. I'll try to take a look tomorrow, get this and some anitimer
issues resolved.

**Comment by demonnic** [comment]
Looking into this a bit today, haven't had the kind of time I'd hoped this weekend.

**Comment by Brenex** [comment]
Here is my fix: https://github.com/Brenex/YATCO

**Comment by Kebap** [comment]
This seems interesting, as my game as well sends chat text via GMCP

**Comment by demonnic** [comment]
having moved to EMCO and changed it to be non-chat specific, I think gmcp drivers may need to be on a per-game/package basis. Since the name of the end tabbed object is not fixed, and I no longer assume chat is all you want to do with it, and not everyone will want to use the same tab names, it may be easier to instead provide an example on the wiki for EMCO of how you might take a gmcp chat message and redirect it.
